services:

  web:
    build:
      context: ./apps/web
      dockerfile: Dockerfile
    container_name: parque-web
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: development
    volumes:
      - ./apps/web:/app
      - /app/node_modules
      - /app/.next
    networks:
      - parque-network

networks:
  parque-network:
    driver: bridge